### ISSUE TITLE
Static badge generation not working when license name contains special characters

### ISSUE THREAD

**Issue by kefranabg** [kefranabg/readme-md-generator#132]
**Describe the bug**
Static badge generation not working when license name contains special characters. Example `Apache-2`

**To Reproduce**

- In your `package.json`, add `"license": "Apache-2"`
- Run readme generator
- Fill license url

**Expected behavior**

Should display a license badge in README with `Apache-2` but we get a 404.

**Additional context**

The issue come from shields.io that cannot contains special characters in url. `readme-md-generator` should skip special chars in license name.

**Comment by tbetous** [comment]
Hi @kefranabg ! Not sure that Apache-2 is correct. If you try with "Apache 2.0" it works fine because the shield url is https://img.shields.io/badge/License-Apache%202.0-yellow.svg

For Apache 2.0 I get :
<a href="https://www.apache.org/licenses/LICENSE-2.0.html" target="_blank">
    <img alt="License: Apache 2.0" src="https://img.shields.io/badge/License-Apache 2.0-yellow.svg" />
  </a>

IMO, it is  just a typo error.

**Comment by kefranabg** [comment]
When created with github, license keywords might contains `-`.

**Comment by Zenigata** [comment]
I am looking onto it right now.

**Comment by dexterastin** [comment]
If the issue isn't over yet, can I try it?

**Comment by Zenigata** [comment]
The review is ongoing there: https://github.com/kefranabg/readme-md-generator/pull/141. Sorry to not have linked those.

**Comment by kefranabg** [comment]
Fixed in #141
